### ISSUE TITLE
You might want to add a message to console.error()

### ISSUE THREAD

**Issue by folkertjan** [MitchGoudkuil/web-app-from-scratch-18-19#1]
It's nitpicking, but it might help you out later on.
On its own, console.error() doesn't do anything, like console.log() wouldn't do anything. It might be helpful when connection issues or API downtime cause issues, you can see what's going on by changing `console.error()` to `console.error(err)`
https://github.com/MitchGoudkuil/web-app-from-scratch-18-19/blob/218fa13d4fbd863ed8dd69c47b4e22f26dd57b6a/week1/public/js/app.js#L61-L63

**Comment by maanlamp** [comment]
@follywolly Nice catch!

You could als use `console.error` as the function to be called by `.catch` directly, instead of an unnecessary enclosing function!

```js
Promise.catch(err => { 
   console.error(err) 
 })

//Is the same as

Promise.catch(console.error)
```

**Comment by folkertjan** [comment]
@maanlamp Ah nice one. Forgot about that!

**Comment by MitchGoudkuil** [comment]
Thanks for the feedback, logging the errors now.
