### ISSUE TITLE
One big function

### ISSUE THREAD

**Issue by JimvandeVen** [MitchGoudkuil/web-app-from-scratch-18-19#2]
https://github.com/MitchGoudkuil/web-app-from-scratch-18-19/blob/218fa13d4fbd863ed8dd69c47b4e22f26dd57b6a/week1/public/js/app.js#L9

In the function `getPokemon()` you now do (almost) everything. It would maybe be better to seperate the different actions you take inside that function. This way you have specific functions do specific things. This is also a good 'best practice' to keep in mind.

**Comment by maanlamp** [comment]
Nice catch! @JimvandeVen 

To elaborate:
Calling a function `getPokemon` makes me assume you _**get pokemon**_. You're not only getting them, but also doing _literally_ **everything else**.

Consider rewriting them into smaller functions as such:
```js
function getPokemon() {...}
function filterPokemon() {...}
function doSomethingElse() {...}
function appendPokemonToBody() {...}

getPokemon()
  .then(filterPokemon)
  .then(doSomethingElse)
  .then(appendPokemonToBody)
```

That's not only more maintainable, but it's so much easier to read! :)

**Comment by MitchGoudkuil** [comment]
Working with modules now and separate functions. Thanks for the feedback Jim!
